name: CI

on:
  # every git push (to any branch)
  push:
    branches:
      - main
    # do not run CI for documentation-only changes
    paths-ignore:
      - 'ai/**'
      - 'docs/**'
      - '**/*.md'
      - '!.changeset/*.md'
  # pull‐request events *against* main, for the "merge-commit" build
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    # do not run CI for documentation-only changes
    paths-ignore:
      - 'ai/**'
      - 'docs/**'
      - '**/*.md'
      - '!.changeset/*.md'

env:
  CI: 1
  HUSKY: 0
  PLAYWRIGHT_BROWSERS_PATH: .playwright-browsers
  VERCEL_TELEMETRY_DISABLED: 1

permissions:
  contents: read

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      # fetch code
      - uses: actions/checkout@v4

      # install node, pnpm, and package dependencies
      - name: Setup pnpm and install dependencies
        uses: ./actions/install-dependencies
